### ISSUE TITLE
New ui: JS Console Cursor sits below terminal char

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1195]
### Short Summary

The JS Console, in the bottom pane has it's cursor sitting a whole line below the terminal input symbol, ie. 
```
>
 |
````

### Additional Information

<img width="282" alt="screen shot 2016-03-29 at 3 26 26 pm" src="https://cloud.githubusercontent.com/assets/655154/14125982/f43a280e-f5c2-11e5-9323-6618d3aa936d.png">

**Comment by mitchell-as** [comment]
I'm not seeing this on master. If I press Shift+Enter I can put the cursor on the line below the '>', but that's expected.

**Comment by cgchoffman** [comment]
I'm still seeing it on master on Windows.

**Comment by mitchell-as** [comment]
Sorry, I was too hasty then.

**Comment by Naatan** [comment]
Should be fixed now.

**Comment by cgchoffman** [comment]
I just pulled in the latest and ran `bk build` but I'm still seeing this.  The input indicator is green now, so taht's new!
![capture](https://cloud.githubusercontent.com/assets/655154/14863998/f3cac200-0c6c-11e6-9583-f0090022b8de.PNG)

**Comment by Naatan** [comment]
Weird, must be something specific to windows.

**Comment by tonyattwood** [comment]
Hello,

Here  are  some interesting facts you may  be  interested  in, I think this  information could be helpful, read it here <http://fast.the-burnett-family.com/e4hbyt>

Wishes, tony.attwood@ntlworld.com
