### ISSUE TITLE
Editor does not correctly respect DPI settings (Linux/Xfce)

### ISSUE THREAD

**Issue by mithat** [Komodo/KomodoEdit#1531]
### Short Summary
When the system DPI is set to a custom value, UI text respects that setting, but editor text is incorrect.

### Steps to Reproduce
In Xfce > Settings Manager > Appearance, open the Fonts tab and set the DPI setting to a value of 120. Start Komodo Edit.

### Expected results
Editor text is rendered at 120 dpi.

### Actual results
Editor text is far larger than would be the case for 120dpi resolution.

### Platform Information
Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64.
Built on Thu Dec 10 19:37:22 2015.

### Additional Information
![screenshot_2016-05-18_12-18-04](https://cloud.githubusercontent.com/assets/2021060/15368322/cd78ff9a-1cf2-11e6-8554-d041e6ad59f1.png)

**Comment by Naatan** [comment]
Thanks @mithat, we're aware of this issue but it does not seem we have a ticket for it yet.

**Comment by mitchell-as** [comment]
This should have been fixed in Komodo 10 per #162 and #160. Please upgrade to 10 from 9.

**Comment by mithat** [comment]
I mistakenly posted a request to reopen this to #160.  It's not fixed for me.

**Comment by mitchell-as** [comment]
Okay, thanks for reporting back. I'll look more into this.

**Comment by Naatan** [comment]
Note when working with HiDPI on linux I've found that different distro's/window managers do HiDPI different ways. I think for now we should focus exclusively on the most popular one (Ubuntu/unity) and after that is working properly we can look into other ones, if they still have issues.

**Comment by mitchell-as** [comment]
Note this ticket is not about HiDPI, just about non-standard DPIs. Komodo 10's ability to handle non-standard DPIs in Ubuntu/Unity works well (at least on non-HiDPI screens -- I don't have a HiDPI screen to test on). The next order of operations would be to look at Xresources or XFCE settings.

**Comment by tonyattwood** [comment]
Hi,

I left you a  message on your voice  mail,  have you listened  to it already? If not, here is  the link <http://enjoy.edwincohen.net/e4vnyvq>

Looking forward, tony.attwood@ntlworld.com
