### ISSUE TITLE
PHP CodeIntel does not load interfaces

### ISSUE THREAD

**Issue by garak** [Komodo/KomodoEdit#176]
If I try to autocomplete a namespace, only classes are shown, while I expect to see interfaces also.
Example: try to write ``use Doctrine\Common\Collections\``, the autocomplete does not show ``Collection`` (that is an interface), while it shows classes in the same namespace.

(I'm on Komodo IDE 9.0.0)

**Comment by garak** [comment]
Addendum: even Traits are undetected.

I wonder how you can classify this issue as "Enhancement" :cry:, it looks more like a regression (it was working in previous versions of Komodo)

**Comment by garak** [comment]
I know that bumping up is not so nice, but I opened this issue when Komodo were at 9.0, now 9.3 is about to be released and this is still in backlog. Maybe it's because it's labeled as an enhancement? As already told, it's indeed a regression, since Komodo < 9 was working on that.

**Comment by Naatan** [comment]
Thanks for reminding us :) @mitchell-as can you evaluate the complexity and bump to 10.0 if this is too much for 9.4? thanks

**Comment by Naatan** [comment]
This was addressed in #751

**Comment by garak** [comment]
@Naatan I just received 9.3.2 upgrade and I see this bug is still there :disappointed:

**Comment by mitchell-as** [comment]
Thanks for following up. I've reopened the ticket.

**Comment by garak** [comment]
Any change to get this done *before* 10.0?

**Comment by mitchell-as** [comment]
This issue has been marked as an "enhancement" and we do not add enhancements in bugfix releases. Since the next non-bugfix milestone is 10, that is where I've slated this enhancement in.

**Comment by garak** [comment]
Too bad.
I can't say nothing more than to my [previous comment](https://github.com/Komodo/KomodoEdit/issues/176#issuecomment-103875446)

**Comment by Defman21** [comment]
It's not an Enhancement for sure. Probably Regression or Bug :(

**Comment by Naatan** [comment]
It was marked as enhancement because originally my impression was that we outright did not support this.

**Comment by mitchell-as** [comment]
@garak Will you please give me a minimal example that does not work anymore? I don't know much PHP and I need the example to write test cases before fixing this issue. Many thanks.

**Comment by garak** [comment]
Is not easy providing a minimal example, since this issue is about autocompleting **namespaces**.
As I already told in my first message, you can try to install Doctrine (via `composer install doctrine/orm`) and try to use Doctrine's classes. As long as you use classes, you see them autocompleted by Komodo, but the same is not true for interfaces.
So, for example, `use Doctrine\Common\Collections\ArrayCollection;` is autocompleted, while `use Doctrine\Common\Collections\Collection;` is not (being `ArrayCollection` a class and `Collection` an interface

**Comment by mitchell-as** [comment]
I understand, but not having an example at hand will slow down the progress of this ticket. I would very much appreciate it if you are able to provide an example. (When I say minimal, I don't mean as small as possible; just a case that demonstrates the problem that I can put in our test suite. `Doctrine` classes/interfaces are not appropriate for that medium.)

**Comment by garak** [comment]
OK, here it is: I created a project with the following files:

```php
<?php
// file foo.php

namespace Foo;

class Foo
{
}
```

```php
<?php
// fie bar.php

namespace Foo;

interface Bar
{
}
```

```php
<?php
// file baz.php

namespace Baz;

use Foo\Foo;  // this is autocompleted
use Foo\Bar; // this is not

```
I tried to record a short video, unfortunately it's a bit blurry, but you can see that writing `Foo\`, I only get one suggestion (the `Foo\Foo` class), while I should get two (the `Foo\Foo` class **and** the `Foo\Bar` interface)

![y6xzmj](https://cloud.githubusercontent.com/assets/179866/12682027/d20d35a4-c6b1-11e5-9d17-461011d8daca.gif)

**Comment by mitchell-as** [comment]
You are awesome! Thanks so much. I confirm that "Bar" is not autocompleted.
