### ISSUE TITLE
Code intel doesn't always shutdown with Application stop

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2655]
### Short Summary

I can't figure out any pattern yet but something to be aware of.  I often can't rebuild Komodo because the code intel Python process is still running and holding on to files in the mozilla build directory that it uses.  I have to force kill the process then I can build Komodo again.

**Comment by Naatan** [comment]
Please share the pystderr.log and codeintel3.log when you see codeintel is still running after Komodo stopped (before restarting).

**Comment by cgchoffman** [comment]
Yes for sure, I didn't know that exists.  I have a bad habit of ignore the always empty codeintel.log file.

**Comment by cgchoffman** [comment]
Logs while codeintel process still running but Komodo is stopped:
[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1076009/codeintel3.txt)

**Comment by Naatan** [comment]
What about pystderr.log? I need both :)

**Comment by cgchoffman** [comment]
That log may not have been from the hanging code intel process.  I've just been doing `bk build quick` to load changes in JS files but I had to do a full rebuild of the codeintel module and finally noticed that codeintel was still running.  It could have been running for some time now.

**Comment by Naatan** [comment]
Ok, please share both logs when you know for a fact the issue has presented itself (on that particular run), otherwise I cannot do anything. You could keep your task manager open to see if the process quits.

**Comment by cgchoffman** [comment]
Oh i only saw you ask for codeintel3.log.  Too late now.  I'll watch for a hanging process.

**Comment by cgchoffman** [comment]
Here you go!
[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1076039/codeintel3.txt)
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1076040/pystderr.txt)

**Comment by Naatan** [comment]
One thing that stands out is codeintel is complaining about a column not existing. This column was introduced recently but would require a new db. Try deleting your codeintel db from your profile folder and running Komodo again. See if that helps with this issue.

**Comment by Naatan** [comment]
Also might be worth adding a `console.error(event)` on line 81 of tcp.js, see if that gives us any more info.

**Comment by cgchoffman** [comment]
Deleted codeintel db and added suggested log line in tcp.js at line 81:
[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1076131/codeintel3.txt)
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1076130/pystderr.txt)

**Comment by Naatan** [comment]
And that pystderr.log is from after you shut down Komodo right? Before starting it again.

**Comment by cgchoffman** [comment]
It should be yes.

**Comment by Naatan** [comment]
Strange, when I shut down Komodo there is a lot more info in the log. Did you kill the process maybe?

**Comment by cgchoffman** [comment]
I don't think so but it happens constantly.  I had 4 processing going at one point.  I can't get another set of logs for you.

**Comment by cgchoffman** [comment]
No restart.  Definitely came from the last run Komodo:
[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1078487/codeintel3.txt)
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1078486/pystderr.txt)

**Comment by cgchoffman** [comment]
I just noticed something.  I've have to rebuild the Code intel module more lately and I started getting *Permission denied* errors when doing `bk build` as that has to access *komodo.exe* in the mozbuild dir.

I reproduced this on a random shutdown and watched the *Komodo.exe* process moves from  the *Apps* section of Task Manager to *Background Processes* then hangs around for a while.  It takes about 10 seconds or more for that process to finally die.  I have no idea if this is causing Code intel to hang around as well but it seems likely.  The Codeintel process never seems to die.

**Comment by cgchoffman** [comment]
I THINK i've noticed a pattern that when the codeintel process hangs THAT is when the Komodo.exe process also hangs around for a while.  So maybe Komodo.exe sent a kill command and is waiting for a response but codeintel never answers but somehow Komodo is still able to eventually close after approx 10 seconds.

**Comment by cgchoffman** [comment]
I was waaaaay off on that time estimate.  Just timed it and it was more like a minute that the komodo.exe process stuck around for.  Connection timeout?

**Comment by cgchoffman** [comment]
Now that I have debug logging turned on for jsonrpc.js I can see that the codeintel process just stops responding at some point.  No matter what call is sent no responses are send back.

I still can't figure out to make it hang but it doesn't take long.

**Comment by Naatan** [comment]
Does it stop responding before you even initiate a shutdown?

**Comment by cgchoffman** [comment]
Long before.  I just never noticed that codeintel stopped responding because I didn't have jsonrpc.js logging turned on.

**Comment by Naatan** [comment]
See if you can figure out what call it stops on.

**Comment by cgchoffman** [comment]
I've consistently seen the following as the last log line in codeintel3.log
```
[2017-06-16 11:43:42,812] [ERROR]  JsonRPC: Failed calling API method: getCaretScope
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\extensions\codeintel@activestate.com\pylib\codeintel\lib\server\jsonrpc.py", line 42, in process
    result = method["function"](*request["params"])
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\extensions\codeintel@activestate.com\pylib\codeintel\lib\service\__init__.py", line 161, in getCaretScope
    scope = language.scanner.scan(buf)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\javascript\scanner.py", line 3778, in scan
    return super(NodeJSScanner, self).scan(filename, env)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\javascript\scanner.py", line 1101, in scan
    scope.define(v.toAbstractSymbol(scope))
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\javascript\scanner.py", line 548, in toAbstractSymbol
    symbol.define(v.toAbstractSymbol(symbol))
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\javascript\scanner.py", line 548, in toAbstractSymbol
    symbol.define(v.toAbstractSymbol(symbol))
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\javascript\scanner.py", line 548, in toAbstractSymbol
    symbol.define(v.toAbstractSymbol(symbol))
AttributeError: 'Import' object has no attribute 'define'
```

But when I restart I can trigger a rescan of that file over and over and over again without a hang.  it seems to just take time and eventually the server hangs.

**Comment by cgchoffman** [comment]
"that file" is *symbolbrowser.js* btw.

**Comment by Naatan** [comment]
@mitchell-as please check out that error.

**Comment by mitchell-as** [comment]
I've committed a fix.

**Comment by Naatan** [comment]
@cgchoffman update your codeintel (`git submodule update --remote`) and see if it still happens?

**Comment by cgchoffman** [comment]
I'm still getting the hung code intel processes using the latest code intel commits.

**Comment by Naatan** [comment]
Anything else consistent in the error log?

**Comment by mitchell-as** [comment]
I don't know what the current status on codeintel3 in Komodo, but it's possible you opened a file that the new scanners are choking on (infinite loop) and a clean shutdown is not possible. Try enabling debug logging and see if codeintel3.log gives anything interesting. @Naatan can probably tell you how to enable debug logging from Komodo. I don't know how to do that.

**Comment by Naatan** [comment]
Just add a `-d` flag at process.js line 65.

**Comment by cgchoffman** [comment]
The log file is so big with `-d` that it almost crashed notepad... so here is the last 30ish lines of the file:
[codeintel3-snipped.txt](https://github.com/Komodo/KomodoEdit/files/1110097/codeintel3-snipped.txt)
and the pysterr.log:
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1110098/pystderr.txt)

**Comment by mitchell-as** [comment]
I would have expected to see some logs from `src/servicethread.py` like "Stopping serviceThread", "onSocketServerShutdown", "Threaded file scanner stopped", and "Closing Database". Because those log entries are not present, it's highly likely the file scanner is still running.

**Comment by cgchoffman** [comment]
Is that a "note to self" or are you saying that is the correct behavior that it's not shutting down while it's scanning?

**Comment by Naatan** [comment]
He's saying neither, he means the logs should be more verbose. Given that I developed those components it's a note to me.

@cgchoffman you didn't answer my question though, are you still seeing any consistencies between logs?

**Comment by cgchoffman** [comment]
No consistency no.

**Comment by cgchoffman** [comment]
Still seeing this with the latest code intel changes.

**Comment by cgchoffman** [comment]
I just had to kill 5 code intel processes.  I bumped up the priority as we can't release with this happening.  Just want to make sure it doesn't slip.  I realize it's likely up to me as I'm the "Windows Guy" so any pointers on what I could do to investigate would be helpful.

**Comment by Naatan** [comment]
I've seen it happen on Linux, so not likely just up to you. If we can't find repro steps I can just make it more aggressive in regards to killing the codeintel process.

**Comment by Naatan** [comment]
Should be fixed with https://github.com/Komodo/KomodoIDE/commit/ed601cf4713440e4e9582156f139dbc6ce5a21c8
