### ISSUE TITLE
Wrong colors in abyss skin

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#290]
When you have the vertical tabs enabled,
![snap 2015-05-25 at 10 24 50](https://cloud.githubusercontent.com/assets/3530262/7794233/56eabf52-02c8-11e5-8651-678080f9184f.png)
the tab-headers arent styled in the black theme,
![snap 2015-05-25 at 10 26 45](https://cloud.githubusercontent.com/assets/3530262/7794278/e0448652-02c8-11e5-877f-1bc885ae7b54.png)
reported the bug before only on the abyss skin
https://github.com/Komodo/Abyss-Skin/issues/2

**Comment by Naatan** [comment]
Should be fixed in the next nightly. 

https://github.com/Komodo/KomodoEdit/commit/6510782f64fc946a0a813da61e3a509664aef9ca

**Comment by babobski** [comment]
@Naatan updated to the latest nightly, but the problem isn't fixed, still got my ugly headers..

**Comment by Naatan** [comment]
Try installing Abyss from here > http://komodoide.com/packages/skins/abyss/

**Comment by babobski** [comment]
installed the theme separate but didn't fixed the headers.
But now its not integrated in komodo, i used the DOM inspector to find a fix for it, messed around with the theme and found out what was causing the ugly headers.
There was a <code>-moz-appearance: -moz-win-browsertabbar-toolbox;</code> enabled on the headers (<code>ko-pane .tabs-vertical-label</code> in file chrome://komodo/skin/bindings/widgets.css). This was causing the ugly gradient (in all themes).
I will create a pull request for the fix(abyss skin).
