### ISSUE TITLE
PHP autocompletion seems broken in Komodo 11

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3102]
### Short Summary
If created my first WordPress project in Komodo 11.
But my WordPress autocompletion is missing ( `the_title()`, etc. ).

### Steps to Reproduce
Create a clean WordPress install as described [here](https://github.com/Komodo/KomodoEdit/issues/2250#issuecomment-270159092)

### Expected results
Getting WordPress autocompletions.

### Actual results
They are missing.

### Platform Information
Komodo Ide 11.0.0 build 90651 windows 10

### Error-log
```
[2017-09-15 16:35:08,476] [INFO] Startup: Welcome to Komodo IDE 11.0.0 build 90651 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2017-09-15 16:35:08,476] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\komodo.exe built on Mon Sep 04 23:00:27 2017
[2017-09-15 16:35:14,742] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-09-15 16:35:16,927] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-09-15 16:35:19,763] [DEBUG] console: log: Less has finished and no sheets were loaded.
[2017-09-15 16:35:21,690] [WARNING] console-logger: Use of Mutation Events is deprecated. Use MutationObserver instead. (1) in chrome://komodo/content/bindings/scrolltabs.xml:1184
[2017-09-15 16:35:28,279] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-09-15 16:35:28,313] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2017-09-15 16:35:28,818] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2017-09-15 16:35:38,335] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-09-15 16:35:39,223] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-09-15 16:35:39,588] [INFO] komodospellchecker: Spell checker loaded.
[2017-09-15 16:35:39,588] [INFO] komodospellchecker: Using dictionary en-US
[2017-09-15 16:35:40,134] [INFO] codeintel/process: Starting CodeIntel
[2017-09-15 16:35:40,137] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2017-09-15 16:35:42,411] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-09-15 16:35:43,630] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-09-15 16:35:44,572] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
[2017-09-15 16:35:45,647] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-09-15 16:35:45,674] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-09-15 16:35:45,721] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-09-15 16:35:45,796] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for Less
[2017-09-15 16:35:45,796] [WARNING] koLanguage: Asked for unknown language: 'None'
[2017-09-15 16:35:47,497] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-09-15 16:35:47,499] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-09-15 16:35:47,499] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-09-15 16:35:47,509] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-09-15 16:35:47,509] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-09-15 16:35:47,509] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-09-15 16:35:47,586] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koamAddonManager.js:138
[2017-09-15 16:35:48,940] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-09-15 16:35:48,940] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-09-15 16:35:48,940] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-09-15 16:35:49,427] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/toolbar.svg:0
[2017-09-15 16:35:49,427] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2017-09-15 16:35:49,543] [DEBUG] codeintel/process: stdout: 
port:56143

pid:9868

[2017-09-15 16:35:49,545] [INFO] codeintel/process: CodeIntel started on port 56143
[2017-09-15 16:35:49,545] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-09-15 16:35:52,976] [WARNING] console-logger: Unexpected value scale(NaN) parsing transform attribute. (1) in file:///C:/Users/wie_w/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2017-09-15 16:35:52,976] [WARNING] console-logger: Unexpected value NaN parsing width attribute. (1) in file:///C:/Users/wie_w/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2017-09-15 16:35:52,977] [WARNING] console-logger: Unexpected value NaN parsing height attribute. (1) in file:///C:/Users/wie_w/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2017-09-15 16:35:52,977] [WARNING] console-logger: Unexpected value 0 0 NaN NaN parsing viewBox attribute. (1) in file:///C:/Users/wie_w/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2017-09-15 16:35:53,417] [ERROR] console-logger: NS_ERROR_NOT_AVAILABLE:  (2) in chrome://komodo/content/sdk/icons.js:609
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/icons.js", line 609, in 

[2017-09-15 16:35:53,632] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2017-09-15 16:35:53,634] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/110
[2017-09-15 16:35:55,017] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F110 (404)
[2017-09-15 16:35:55,645] [WARNING] koLanguage: Asked for unknown language: 'Django XHTML Template'
[2017-09-15 16:35:55,697] [WARNING] koLanguage: Asked for unknown language: 'Django Text Template'
[2017-09-15 16:35:55,697] [WARNING] koLanguage: Asked for unknown language: 'Django Template'
[2017-09-15 16:35:55,697] [WARNING] koLanguage: Asked for unknown language: 'Laravel Blade Template'
[2017-09-15 16:35:55,697] [WARNING] koLanguage: Asked for unknown language: 'SGML'
[2017-09-15 16:35:55,818] [WARNING] koLanguage: Asked for unknown language: 'Django XML Template'
[2017-09-15 16:35:55,861] [WARNING] koLanguage: Asked for unknown language: 'Smarty Template'
[2017-09-15 16:35:55,869] [WARNING] koLanguage: Asked for unknown language: 'Django HTML Template'
[2017-09-15 16:35:55,977] [WARNING] koLanguage: Asked for unknown language: 'UDL'
[2017-09-15 16:41:07,193] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-09-15 16:41:07,193] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-09-15 16:41:07,194] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-09-15 16:44:39,709] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg?size=14:0
[2017-09-15 16:44:42,144] [ERROR] console-logger: TypeError: callback is not a function (2) in chrome://komodo/content/project/peTemplate.js:77
Traceback (most recent call last):
  File "chrome://komodo/content/project/peTemplate.js", line 77, in 

[2017-09-15 16:45:14,694] [DEBUG] codeintel/feature/completions: Cancelling completion, uuid is no longer active
[2017-09-15 16:45:14,878] [DEBUG] codeintel/feature/completions: Cancelling completion, uuid is no longer active
[2017-09-15 16:50:40,953] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg?size=14:0
[2017-09-15 16:50:42,734] [ERROR] console-logger: TypeError: callback is not a function (2) in chrome://komodo/content/project/peTemplate.js:77
Traceback (most recent call last):
  File "chrome://komodo/content/project/peTemplate.js", line 77, in 

[2017-09-15 16:56:24,759] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg?size=14:0
[2017-09-15 17:05:02,467] [ERROR] console-logger: TypeError: callback is not a function (2) in chrome://komodo/content/project/peTemplate.js:77
Traceback (most recent call last):
  File "chrome://komodo/content/project/peTemplate.js", line 77, in 

[2017-09-15 17:11:03,651] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg?size=14:0
[2017-09-15 17:11:06,174] [ERROR] console-logger: TypeError: callback is not a function (2) in chrome://komodo/content/project/peTemplate.js:77
Traceback (most recent call last):
  File "chrome://komodo/content/project/peTemplate.js", line 77, in 

[2017-09-15 17:34:14,381] [WARNING] koLanguage: Asked for unknown language: 'Django XHTML Template'
[2017-09-15 17:34:14,381] [WARNING] koLanguage: Asked for unknown language: 'Django Text Template'
[2017-09-15 17:34:14,381] [WARNING] koLanguage: Asked for unknown language: 'Django Template'
[2017-09-15 17:34:14,381] [WARNING] koLanguage: Asked for unknown language: 'Laravel Blade Template'
[2017-09-15 17:34:14,382] [WARNING] koLanguage: Asked for unknown language: 'SGML'
[2017-09-15 17:34:14,384] [WARNING] koLanguage: Asked for unknown language: 'Django XML Template'
[2017-09-15 17:34:14,384] [WARNING] koLanguage: Asked for unknown language: 'Smarty Template'
[2017-09-15 17:34:14,384] [WARNING] koLanguage: Asked for unknown language: 'Django HTML Template'
[2017-09-15 17:34:14,385] [WARNING] koLanguage: Asked for unknown language: 'UDL'
[2017-09-15 17:36:19,151] [WARNING] koLanguage: Asked for unknown language: 'Django XHTML Template'
[2017-09-15 17:36:19,153] [WARNING] koLanguage: Asked for unknown language: 'Django Text Template'
[2017-09-15 17:36:19,153] [WARNING] koLanguage: Asked for unknown language: 'Django Template'
[2017-09-15 17:36:19,154] [WARNING] koLanguage: Asked for unknown language: 'Laravel Blade Template'
[2017-09-15 17:36:19,154] [WARNING] koLanguage: Asked for unknown language: 'SGML'
[2017-09-15 17:36:19,154] [WARNING] koLanguage: Asked for unknown language: 'Django XML Template'
[2017-09-15 17:36:19,155] [WARNING] koLanguage: Asked for unknown language: 'Smarty Template'
[2017-09-15 17:36:19,155] [WARNING] koLanguage: Asked for unknown language: 'Django HTML Template'
[2017-09-15 17:36:19,157] [WARNING] koLanguage: Asked for unknown language: 'UDL'
[2017-09-15 17:54:48,289] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-15 17:54:48,289] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-15 17:54:48,289] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by mitchell-as** [comment]
Thanks for the report.

@Naatan I think this has to do with the fact that we are not auto-importing all PHP files anymore, but explicitly requiring `require()`, `include()`, etc. statements to fetch globals and such. Should we revise this stance and auto-import everything?

**Comment by Naatan** [comment]
@mitchell-as can you explain the implications again?

**Comment by mitchell-as** [comment]
@Naatan this will require fetching all files in sub-directories (or the project? I'm not sure how we would figure out what PHP files to auto-import), and then for each file found, fetch all of its top-level symbols and import them into the current namespace. There will be performance implications. It's just a matter of how much of a hit it will be.

**Comment by Naatan** [comment]
I'm not exactly sold on the idea, but I don't see another way around it. Let's see what the performance implications are and take it from there.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/0b4935a3fc5f40c1866fd75c9713d360ca1c2549. We'll see how performance goes for larger projects.

**Comment by mjbrancato** [comment]
You guys marked my issue as a duplicate and marked it as closed?

This is still not working for me in Linux: http://prntscr.com/gslt1m

Please see screenshot, a menu doesn't popup with the explanation and then showing usage, array_push($haystack, $array_variable);

**Comment by mitchell-as** [comment]
Hi, it was not marked as a duplicate. That's Github's fault for being confusing when showing linked issues. I'll look into this again.

**Comment by mjbrancato** [comment]
@mitchell-as it says you marked it as duplicate/linked and added a comment with it: http://prntscr.com/gstlis

If that wasn't you then I understand. GitHub should really get their issues fixed.

**Comment by mjainQA** [comment]
Verified in 11.0.1 nightly

**Comment by codermjb** [comment]
Works for me as well even after wiping out localhost and restarting Komodo.
