### ISSUE TITLE
Golang - need to manually add go to PATH even though Komodo technically knows what it is

### ISSUE THREAD

**Issue by technopoetic** [Komodo/KomodoEdit#952]
Same issue as Issue #587 
I see where that issue was closed, but I don't see what the actual fix was.  Build info is below.
Komodo IDE, version 9.3.0, build 88117, platform linux-x86_64.
Built on Thu Oct 29 11:07:23 2015.

I've tried setting my paths directly in the IDE preferences, but still no joy. 
Here is the output from the macro referenced in Issue #587 
env: PATH = /home/rhibbitts/.local/bin:/home/rhibbitts/.rvm/bin:/home/rhibbitts/bin:/usr/local/go/bin:/home/rhibbitts/code/golang/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/rhibbitts/.local/bin:/home/rhibbitts/bin:/home/rhibbitts/.local/bin:/home/rhibbitts/bin
env: GOROOT not found.
env: GOPATH = /home/rhibbitts/code/golang
which: godef = /home/rhibbitts/code/golang/bin/godef
which: gocode = /home/rhibbitts/code/golang/bin/gocode
which: gofmt = /usr/local/go/bin/gofmt

Of course, when run from the UI, no path info is found.

**Dev Edit:**

https://github.com/Komodo/KomodoEdit/issues/952#issuecomment-226569859

**Comment by Naatan** [comment]
This is fixed in the latest nightly: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by technopoetic** [comment]
Just installed latest nightly:
Komodo IDE, version 9.3.2, build 88190, platform linux-x86_64. Built on Mon Dec 7 04:23:16 2015

Still happening:
[2015-12-14 12:31:43,381] [ERROR] codeintel.go: Error compiling outline: Unable to compile 'outline.go'[Errno 2] No such file or directory: 'go'

Is there something else that I need to do?

**Comment by Naatan** [comment]
You may have to reconfigure Golang.

**Comment by technopoetic** [comment]
Reconfigure Golang... Meaning explicitly set the paths in the IDE preferences?

**Comment by technopoetic** [comment]
I've tried it both ways, "Find on Path", and set explicitly.  Still getting the error.
In addition, I've started seeing variations on this error:
`'NoneType' object has no attribute 'get' `
Which I presume is part of the code intel issue.

**Comment by Naatan** [comment]
Could you try configuring it on a clean profile? 

Help > Troubleshooting > Restart in Safe-Mode.

**Comment by technopoetic** [comment]
Still doesn't work.  I'm fairly certain it's a path issue.  If I go into komodo-go/pylib/codeintel_go.py and hard code get_go_exe to return /usr/local/go/bin/go then everything works properly.  Well, gofmt still deletes the whole file, but it's progress.

**Comment by Naatan** [comment]
Ahh hold on, are you using the addon? If so please uninstall. Komodo 9.3 has GO built-in.

**Comment by technopoetic** [comment]
No.  I was able to get it to work by installing the addon, but the issue is
there with the base install.  I've also tried starting in safe mode, and a
complete purge and re-install.

Richard Hibbitts
Web & Application Developer
http://technopoetic.com
@technopoetic <http://twitter.com/technopoetic>
(919) 386 - 9321

**Comment by Naatan** [comment]
And after that (a complete purge) the error is still the exact same as in your first post?

**Comment by technopoetic** [comment]
Exactly.  I've been poking around in Komodo-IDE-9/lib/mozilla/extensions/golang@activestate.com/pylib/codeintel_go.py and it's the same as I mentioned about the add-on.  If I change get_go_exe() to explicitly return my Go binary, then all is well.  With the default code, in some instances, it's not able to find the go binary.  I added some extra logging just to see what's going on, and I occasionally see things like this:
`[2015-12-15 12:31:51,625] [WARNING] codeintel.go: Path is: [u'/home/rhibbitts/.local/bin', u'/home/rhibbitts/.rvm/bin', u'/home/rhibbitts/bin', u'/usr/local/go/bin', u'/home/rhibbitts/code/golang/bin', u'/usr/lib64/qt-3.3/bin', u'/usr/lib64/ccache', u'/usr/local/bin', u'/usr/bin', u'/bin', u'/usr/local/sbin', u'/usr/sbin', u'/home/rhibbitts/.local/bin', u'/home/rhibbitts/bin', u'/home/rhibbitts/.local/bin', u'/home/rhibbitts/bin']
[2015-12-15 12:31:54,195] [WARNING] codeintel.go: Path is: []`

Those log entries are only seconds apart, with no changes to the code at all.  I have no idea why the path would be populated in one case, but not the other.

So, the end result seems to be that it can't get a good path, so line 380 in codeintel_go.py just throws the string "go" into the path array.  In that case, which.py isn't able to find the command, so you get errors.  What's strange, is that very occasionally, it seems to work.  Maybe a race condition going on somewhere?

As far as I'm concerned, I've got a work-around, so it's usable.  I may keep looking at it myself, just to satisfy my curiosity, but

**Comment by Naatan** [comment]
What is your distro, and how did you install Go?

**Comment by technopoetic** [comment]
Fedora 22 64 bit.
I installed Go by following the instructions at: https://golang.org/doc/install
Basically downloaded the tarball.  Extracted the tarball to /usr/local then added /usr/local/go/bin/ to my path.

**Comment by Naatan** [comment]
Thanks, I'll have a go at trying this on Fedora 22 after the holidays (seeing as you found a workaround).

**Comment by technopoetic** [comment]
Thanks for the help Naatan.  I appreciate it.

**Comment by Naatan** [comment]
@mitchell-as this needs a fresh set of eyes, please have a look :)

**Comment by mitchell-as** [comment]
Okay, here are my findings:

0. Start with no Go on my system at all.
1. Download a Linux go binary package from the link mentioned earlier.
2. Extracted the download to `/usr/local/go`, also as mentioned earlier.
3. Typed `go` in my shell in order to ensure no `go` could be found (I haven't added to my `PATH yet.) Check.
4. Opened Komodo and opened `/usr/local/go/test/64bit.go`.
5. Confirmed the "Error compiling outline" error as noted in the original post.
6. Closed Komodo.
7. Added `/usr/local/go/bin` to my `$PATH` (`export PATH=$PATH:/usr/local/go/bin`) via the terminal.
8. Started Komodo from that same terminal.
9. Komodo re-opened the `64bit.go` file and I no longer get any errors. My code intelligence and code browser works.
10. When I go to Edit > Preferences > Environment > PATH, I see that `/usr/local/go/bin` is indeed there at the end.

From this I conclude that there are no issues if your Go bin path is in Komodo's recognized `PATH`.

**Comment by wttw** [comment]
As documented in #1528, I see this issue (on OS X) when go is in the path available to Komodo (both the inherited environment and the path configured inside Komodo). Might be OS X / homebrew specific?

**Comment by cgchoffman** [comment]
I'll give this a "GO" on my macbook...get it??  (cough)...I'll report back.

**Comment by Naatan** [comment]
If this solution works consistently we should consider setting it automatically based on the location of someones go executable.

**Comment by cgchoffman** [comment]
Clean profile, No Go installed, OSX 10.11.3, Komodo X:
- installed Go from golang.org using pkg file
- Automatically added to path in the commandline (but not in a way that Komodo can see it)
- GO commands work in the terminal
- **Start Komodo from that terminal**,  open Go file, Code Browser works


- **Start Komodo through Finder**, Open Go File, I get the `Error compiling outline` and code browser isn't working
- Open Preferences > Environment, PATH does not show Go install location (`/usr/local/go/bin`)
- Add > Edit $PATH to include it in the Komodo prefs > Environment
- Apply and close dialog
- Close/Open file, error is gone and Code browser is working.

NOTE: There are still errors about `gocode` or `godef` not existing but I haven't told Komodo where they are and they do not in fact exist :D

Summary, I also conclude that if Go is in a Path that Komodo knows about there is no issue.

Any easy way to test this is to open Tools > Run Command and execute `go` from there. If you get the Go help output then Komodo knows where it is.  Otherwise you will get `/bin/sh: go: command not found` in the Command Output widget.

**Comment by Naatan** [comment]
Ok, let's make this issue about adding the go executable path to the environment automatically.

**Comment by mitchell-as** [comment]
@Naatan I didn't have to touch GOPATH if Go was in my PATH (and thus Komodo's PATH).

**Comment by Naatan** [comment]
Sorry, PATH, not GOPATH.

**Comment by mitchell-as** [comment]
@Naatan  I must be missing something because I don't think there's anything to do in this ticket if Go is in Komodo's PATH. Everything just works. I tried it and @cgchoffman tried it on separate machines without Go previously installed. We put Go in our PATHs and magic happened.

**Comment by Naatan** [comment]
Perhaps I'm just confused because you're using Komodo's PATH to configure it despite there being a preference field for explicitly setting Go's executable. The latter being the preferrable UX. Can you confirm both of those solutions work?

**Comment by cgchoffman** [comment]
- Removed modified path from Komodo prefs
- Restarted Komodo from Finder 
- Code Browser for Go is broken
- open prefs > Languages > Go: point to Go executable explicitly using `Browse` to find it.
- Save prefs and press `Enter` in file to add new line
- Code Browser populates.

**Comment by Naatan** [comment]
Alright then, in that case I'd agree there is no issue here. Least not anymore (it definitely was bugged in the past, but that has since been resolved).

**Comment by cgchoffman** [comment]
If you find this issue and are still having issues please ask in the forums for assistance: 
http://forum.komodoide.com/
It's likely a configuration issue which, while we're happy to help with, is not a bug.  Obviously if through helping you we find there is another bug then we'll open a new issue.

**Comment by wttw** [comment]
Unfortunately my evaluation license has expired, so I can't try it with a current build.

**Comment by Naatan** [comment]
If you contact sales@activestate.com they can extend your trial.
